### ISSUE TITLE
Where is the CFW.bin?

### ISSUE THREAD

**Issue by double-pulsar** [brandonlw/Psychson#21] opened 2014-10-11 03:24 UTC
Where is CFW.bin?
In Running Demo 1 (HID Payload),you write the command:
copy CFW.bin hid.bin
tools\EmbedPayload.exe inject.bin hid.bin
but where is the CFW.bin? where can I download it? thanks

**Comment by faridtm** [comment] 2014-10-11 05:33
i have same problem ? where is the CFW.bin file ???

**Comment by Gaara4** [comment] 2014-10-11 09:27
I use the FW.bin and it works to.

**Comment by double-pulsar** [comment] 2014-10-11 09:59
@Gaara4，Did you success?Use FW.bin

**Comment by cubic3d** [comment] 2014-10-11 12:33
1. Duplicate of #7. Look for issues first, before you open new.
2. There is no _cfw.bin_ in build.bat, it's _fw.bin_.

**Comment by andrei-cb** [comment] 2014-10-11 18:47
https://github.com/adamcaudill/Psychson/releases

**Comment by double-pulsar** [comment] 2014-10-12 02:05
@Caydenz thanks

**Comment by k3rw1n** [comment] 2014-10-12 07:54
you can build it by running the build.bat under the /patch after you install the SDCC.

**Comment by faridtm** [comment] 2014-10-13 15:01
thanks alot.

**Comment by aminazek** [comment] 2014-10-14 00:41
CFW.bin is in the release section. 
https://github.com/adamcaudill/Psychson/releases

Everything has been compiled for you. 

BTW, any difference between CFW.bin and fw.bin?

**Comment by brandonlw** [comment] 2014-10-22 03:58
No, it was just renamed to avoid confusion with any fw.bin you may have...which evidently wasn't accomplished. :)

**Closed as completed by brandonlw** 2014-10-22 03:58 UTC
