### ISSUE TITLE
How Obtaining the Image Burner

### ISSUE THREAD

**Issue by TheW001f** [brandonlw/Psychson#10] opened 2014-10-06 00:38 UTC
hello, first place good job, 
I needed a little help, how can I Obtaining the Image Burner
thank you

**Comment by mtfurlan** [comment] 2014-10-06 04:11
Only method I can find of getting the controller version is to pry open the flash drive and looking on the chip.
Search [this](https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=http%3A%2F%2Fwww.usbdev.ru%2Ffiles%2Fphison%2F&edit-text=&act=url) for BNxx where xx is the controller number

That's how I did it, unsure if it's the way that was intended. That site is linked off of the other links page.

**Comment by cubic3d** [comment] 2014-10-06 04:25
You don't need to open your drive. Use `DriveCom.exe /drive=X /action=GetInfo` to determine the controller.

As mentioned in Wiki, use http://www.usbdev.ru/files/phison/ and look for the "Additional Files" section. These contains the burner images.

**Comment by TheW001f** [comment] 2014-10-06 05:20
ok i use DriveCom.exe /drive=X /action=GetInfo and and then I'll look for the chip ID? I am confused,
thanks for answer if it were not too much to ask if someone had available could give me a hand could add me on Skype my name è mf_854
thank you

**Comment by cubic3d** [comment] 2014-10-06 05:32
As described [here](https://github.com/adamcaudill/Psychson/wiki/Setting-Up-the-Environment), you need to look at this line: `Reported chip type: 2303`. This refers to a PS2251-03 (2303) chip. According to Wiki, this is the only type this software currently supports.

**Comment by mtfurlan** [comment] 2014-10-06 05:40
So what does having a reported chip type of 0000 mean? It is a Patriot 8GB Supersonic Xpres.
Should I just open a separate issue for this?

**Comment by TheW001f** [comment] 2014-10-06 05:44
my Reported chip type is 2303 is I can not use?

**Comment by cubic3d** [comment] 2014-10-06 05:54
@Scuzzball I have no idea, maybe not an Phison chip? Haven't looked into the sources.
@1mf This is the _only_ chip you _can_ use!

**Comment by TheW001f** [comment] 2014-10-06 05:57
sorry this is not,  the Reported chip type is 2233, this not use?

**Comment by cubic3d** [comment] 2014-10-06 06:08
I don't think this has neither been tested nor would work. This project seems to be done by reverse engineering the 2303 chip. @adamcaudill should know it better.

**Comment by TheW001f** [comment] 2014-10-06 06:42
one more question and Kingston 8GB DataTraveler 3.0 T111 this confirmed that the?

**Comment by cubic3d** [comment] 2014-10-06 06:52
It's on the [Supported Devices List](https://github.com/adamcaudill/Psychson/wiki/Known-Supported-Devices). My Kingston DataTraveler 100 G3 8GB have also a 2303.

**Comment by TheW001f** [comment] 2014-10-06 07:43
thanks

**Comment by TheW001f** [comment] 2014-10-06 20:30
I've been looking for the Kingston 8GB DataTraveler 3.0 T111   but have not found just found is this will be? Kingston Digital 8 GB DataTraveler 111 (DT111/8GB)

**Comment by GulfBull** [comment] 2014-10-07 15:34
Both of my DataTraveler 111 had 2302. So be careful.

**Comment by brandonlw** [comment] 2014-10-07 15:55
If the tool reports anything other than 2303, it is not expected to work.

**Comment by ghost** [comment] 2014-10-08 13:20
So I got a 2303 chip and downloaded the firmware_ps2251-03.rar. Which of the .bins do I have to use? There are quite a lot. In the example in the documentation the BN03V104M.BIN is used, but I don't know, if it's good to me as well. I have got the Toshiba TransMemory-MX 16GB black. The output from DriveCom.exe says:

Chip Type: 2303
Chip ID: 98-3A-A8-92-76-57
Firmware version: 2.06.53

So which .bin is the correct one?

**Comment by brandonlw** [comment] 2014-10-08 15:45
I would say try the one in the example.

I have never seen a 2.x firmware version for a 2303 drive. Be sure to get a good dump of that firmware before trying to flash anything.

**Comment by ghost** [comment] 2014-10-09 07:38
Are there good and bad dumps?

**Comment by phaq01** [comment] 2014-10-09 13:42
@CitNils I've ordered the same stick. Could you please leave a not here, which BIN worked for you?

**Comment by ghost** [comment] 2014-10-09 14:20
I used BN03V104M.BIN but if you look at other issues here you will relalize that it did not REALLY work. The stick is useless now. Maybe I need to try manual boot mode, but I haven't yet. But with that BIN I could dump and flash firmware.

**Comment by phaq01** [comment] 2014-10-10 07:19
@CitNils What do you mean by did not REALLY work?

**Comment by ghost** [comment] 2014-10-10 09:26
I cant send firmware right now and got different errors. See here: https://github.com/adamcaudill/Psychson/issues/14

**Comment by Tesrym** [comment] 2014-10-15 20:53
Just got two Datatraveler 111's, 8 and 16 gig variants. Both had 2307 and are useless.

**Comment by brandonlw** [comment] 2014-10-22 03:51
Seeing as how the original question in this issue is resolved, I'm going to close the issue.

**Closed as completed by brandonlw** 2014-10-22 03:51 UTC

**Comment by danielhnmoreno** [comment] 2014-12-08 02:07
Anyone make BadUSB with Datatraveler 111DT 8GB ??

I'm really consufe.

Please contact me

danielhnmoreno[at]gmail.com

**Comment by youarecatched** [comment] 2014-12-25 09:59
I have the problem with the extreme sandisk 16GB  3.0 
??
DriveCom.exe /drive=E /action=GetInfo
Action specified: GetInfo
Gathering information...
Reported chip type: 0000
Reported chip ID: 58-F9-7B-00-98-8E
Reported firmware version: 98.00.00
Mode: Unknown

**Comment by danielhnmoreno** [comment] 2014-12-25 11:53
Probably ur Sandisk is not ps2251-03
=(

Try with DT =)

2014-12-25 7:59 GMT-02:00 youarecatched notifications@github.com:

**Comment by youarecatched** [comment] 2014-12-25 12:22
what is DT ??? name of type usb ?? and i can buy it ..

**Comment by danielhnmoreno** [comment] 2014-12-25 13:46
Data Traveler

DT111 8GB have correct fimware

Maybe G4, but only DT i tested id DT111

=)

2014-12-25 10:22 GMT-02:00 youarecatched notifications@github.com:

**Comment by youarecatched** [comment] 2014-12-25 14:10
oh,, thanks for your help :))

**Comment by youarecatched** [comment] 2014-12-25 14:29
that ?? 
![kingston-datatraveler-g4-8gb](https://cloud.githubusercontent.com/assets/10295514/5554276/2af6cd08-8c7d-11e4-935b-5c767e0e9756.jpg)

**Comment by danielhnmoreno** [comment] 2014-12-25 15:22
NIce, maybe Work, i dont Know

This device is in Know Supported Devices

Please, I Wanna By This DT G4,

test and post results

Thanks

2014-12-25 12:30 GMT-02:00 youarecatched notifications@github.com:

**Comment by youarecatched** [comment] 2014-12-25 16:32
oh .... i wanna know exactly the type of usb ??? 
![kingston_datatraveler_111_8gb](https://cloud.githubusercontent.com/assets/10295514/5554483/cf4e05b4-8c8d-11e4-841c-c6d25d7a2c32.jpg)

**Comment by danielhnmoreno** [comment] 2014-12-25 16:38
???????????

2014-12-25 14:32 GMT-02:00 youarecatched notifications@github.com:

**Comment by youarecatched** [comment] 2014-12-25 16:40
Did you test any usb with badusb sources ?? and successfull ??? u can tell me name off the usb ?? plzzz
